import { prisma } from "../../lib/prisma.js";

export async function seedSkills() {
  const skills = [
    "A/B Testing",
    "Accounting",
    "Adobe XD",
    "Agile",
    "Airflow",
    "Analytics",
    "AWS",
    "Azure",
    "Bloomberg",
    "Budgeting",
    "C++",
    "CI/CD",
    "Compensation",
    "Compliance",
    "Content Strategy",
    "Cost Optimization",
    "CRM",
    "Data Analysis",
    "Data Visualization",
    "dbt",
    "Derivatives",
    "Design Thinking",
    "Digital Marketing",
    "Docker",
    "Employment Law",
    "ERP",
    "Excel",
    "Figma",
    "Financial Modeling",
    "FP&A",
    "GCP",
    "Git",
    "Google Ads",
    "HRIS",
    "HTML/CSS",
    "Incident Response",
    "Java",
    "JavaScript",
    "Kafka",
    "Kubernetes",
    "Lean",
    "Linux",
    "Machine Learning",
    "Microservices",
    "MLOps",
    "Network Security",
    "Penetration Testing",
    "Performance Management",
    "PostgreSQL",
    "Power BI",
    "Process Improvement",
    "Product Strategy",
    "Prototyping",
    "Publications",
    "PyTorch",
    "Python",
    "R",
    "React",
    "Redis",
    "Requirements Gathering",
    "Research",
    "REST APIs",
    "Risk Management",
    "Roadmapping",
    "Security",
    "SEO",
    "SIEM",
    "Six Sigma",
    "Snowflake",
    "Spark",
    "SQL",
    "Stakeholder Management",
    "Statistics",
    "Supply Chain",
    "Tableau",
    "Talent Acquisition",
    "TensorFlow",
    "Terraform",
    "TypeScript",
    "Usability Testing",
    "User Research",
  ];

  await prisma.skill.createMany({
    data: skills.map((name) => ({ name })),
    skipDuplicates: true,
  });

  console.log(`✅ Skills seeded: ${skills.length} skills`);
}
